dist: trusty
sudo: required

language: node_js
node_js:
  - 9

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - stty cols 80

script: npm run test:ci